### ISSUE TITLE
Don't display watcher config when watch is disabled

### ISSUE THREAD

**Issue by coldino** [denosaurs/denon#82]
Hopefully a quick, simple one. The watch config information is always displayed even when the watcher should not be active:
```
[denon] v2.2.1
[denon] watching path(s): *.*
[denon] watching extensions: ts,tsx,js,jsx,json
[denon] starting `deno run --unstable src/mod.ts`
```

I have confirmed the command is not restarted on file changes, as intended for this script, but the output mislead me.

Simply omitting the two '**[denon] watching**' lines would be ideal.

My config has this at the global level, then watch enabled for just one script command. It does not help if I move the watcher config into that script's section.
```yaml
watch: false
watcher:
  paths:
    - denon.yaml
    - importmap.json
    - src
```

Thanks!
