### ISSUE TITLE
Docker: Uncaught NotFound: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by ebebbington** [denosaurs/denon#91]
**Describe the bug**
When running `denon start` (where `start` is a script name),  when i start my container, the shell throws an error. Unsure if it's my environment or denon, but maybe denon is trying to read a file that doesn't exist inside a docker env?

**To Reproduce**
1\. Create the following `docker-compose.yml` file:
```
version: '3'

services:
  server:
    container_name: my_server
    build:
      context: .
      dockerfile: .docker/deno.dockerfile
    volumes:
      - ./src/server:/var/www/server
    working_dir: /var/www/server
    ports:
      - "1667:1667"
    command: bash -c "/root/.deno/bin/denon start"
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge
```
2\. Create the dockerfile:
```
// .docker/deno.dockerfile
FROM debian:stable-slim

RUN apt update -y \
  && apt clean \
  && apt install bash curl unzip -y

RUN curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh -s v1.2.2
RUN export DENO_INSTALL="/root/.local"
RUN export PATH="$DENO_INSTALL/bin:$PATH"
RUN deno install --allow-read --allow-run --allow-write --allow-net -f -q --unstable https://deno.land/x/denon@2.3.2/denon.ts denon
```
3\. Create the `denon.json`:
```
// ./src/server/denon.json
{
  "scripts": {
    "start": {
      "cmd": "deno run app.ts",
      "desc": "Run the server.",
      "allow": [
        "env",
        "net",
        "read",
        "run"
      ]
    }
  },
  "watcher": {
    "interval": 350,
    "exts": ["js", "ts", "json"],
    "match": ["*.*"],
    "legacy": false
  },
  "logger": {
    "fullscreen": false,
    "quiet": false,
    "debug": true
  }
}
```
4\. Create `app.ts`:
```
// ./src/server/app.ts
// empty as it isnt required to have code
```
5\. Start docker: `docker-compose up`
6. See error from shell

**Expected behavior**
Denon should run. the start script and exit cleanly 

**Configuration or Project**
`denon.json` content is supplied above, but the project in it's entirety is at https://github.com/ebebbington/chatsterisk

**Screenshots**
Error response:
![image](https://user-images.githubusercontent.com/47337480/89721906-8ffc5c80-d9da-11ea-81af-7d327372797e.png)

**Setup**

-   OS: macOS
-   Deno version: v1.2.2
-   Denon version: v2.3.2-master
-  Docker version: Docker version 19.03.12, build 48a66213fe

**Additional context**
`/root/.deno/bin/denon --version` works fine, it's just fails when using the script name. I don't know if it's down to a mistake on my part or denon's though.
